config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'
  
  resources :posts, only: [:index, :show] 
  resources :concerts, only: [:index, :show]
  resources :pages, only: :show
  resources :medias, only: :index
  resources :sponsors, only: [:index, :show]
  resources :albums, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :released_at, presence: true
  validates :description, presence: true
  validates :slug, presence: true, uniqueness: true

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :flyer, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :flyer, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :show_at, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :postal_code, presence: true
  validates :street, presence: true
  validates :slug, presence: true, uniqueness: true

  paginates_per 10
  
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  def display_map
      return "https://maps.googleapis.com/maps/api/staticmap?zoom=14&maptype=roadmap&size=400x400
          &markers=color:red%7C#{lat}, #{long}&scale=1"
  end
end

app/models/media.rb
class Media < ActiveRecord::Base
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :content, presence: true
  validates :slug, presence: true, uniqueness: true

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :content, presence: true
  validates :slug, presence: true, uniqueness: true

  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, allow_destroy: true

  paginates_per 5
  
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  def to_s
    label.capitalize
  end
end

app/controllers/albums_controller.rb
class AlbumsController < InheritedResources::Base
  def index
    @albums = Album.order('released_at DESC').page params[:page]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < InheritedResources::Base
  def index
    @concerts = Concert.where(:publish => true).order('show_at ASC').page params[:page]
  end
end

app/controllers/home_controller.rb
class HomeController < InheritedResources::Base
  def index
    @posts = Post.order('created_at DESC').limit(5)
    @concerts = Concert.where('show_at >= ?', Time.now).order('show_at ASC').limit(5)
    @sponsors = Sponsor.limit(3)
    @medias = Media.all
    @album = Album.order('released_at DESC').first
  end
end

app/controllers/medias_controller.rb
class MediasController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  def index
    @posts = Post.where(:publish => true).order('created_at DESC').page params[:page]
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_nav
    @pages = Page.order('title ASC').where(publish: true)
  end
end

app/views/albums/_featured.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Featured Album</h3>
  </div>
  <% if @album %>
    <div class="panel-body no-padding">
      <%= link_to (image_tag @album.cover.url(:medium), class: "img-responsive"), @album %>
    </div>
  <% else %>
    <div class="panel-body">
      <i>No album yet</i>
    </div>
  <% end %>
  <div class="panel-footer">
    <%= link_to "All albums", albums_path %>
  </div>
</div>

app/views/albums/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Albums</li>
</ol>

<div class="row">
    <% @albums.each do |album| %>
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= album.name.capitalize %></h3>
          </div>
          <div class="panel-body no-padding">
            <%= link_to (image_tag album.cover.url(:medium), class: "img-responsive"), album %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/albums/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Albums", albums_path %></li>
  <li class="active"><%= @album.name.capitalize %></li>
</ol>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <h1><%= @album.name.capitalize %></h1>
        <p class="text-justify"><%= @album.description.html_safe %></p>
        <%= image_tag @album.cover.url(:medium), class: "img-responsive" %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Listen</h3>
      </div>
      <div class="panel-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/concerts/_concerts.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Upcoming Concerts</h3>
  </div>
  <% if !@concerts.empty? %>
    <div class="panel-body no-padding">
      <% @concerts.each do |concert| %>
        <div class="clearfix">
          <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 concert-date">
            <%= concert.show_at.day %>
            <%= concert.show_at.strftime("%b") %>
          </div>
          <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <h4><%= link_to concert.name.capitalize, concert %></h4>
            <%= concert.city %>, <%= concert.country %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="panel-body">
      <i>No concert yet</i>
    </div>
  <% end %>
  <div class="panel-footer">
    <%= link_to "All concerts", concerts_path %>
  </div>
</div>

app/views/concerts/_location.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Location</h3>
  </div>
  <% if @concert.lat? && @concert.long? %>
    <div class="panel-body no-padding">
      <%= image_tag @concert.display_map, class: "img-responsive"  if @concert.long and @concert.lat %>
    </div>
    <div class="panel-footer">
      <%= @concert.country %>, <%= @concert.city %></br>
      <%= @concert.street %>
    </div>
  <% else %>
    <div class="panel-body">
      <%= @concert.country %>, <%= @concert.city %></br>
      <%= @concert.street %>
    </div>
  <% end %>
</div>

app/views/concerts/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Concerts</li>
</ol>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Concerts</h3>
  </div>
  <div class="panel-body">
    <% if !@concerts.empty? %>
      <% @concerts.each do |concert| %>
        <h4><%= link_to concert.name.capitalize, concert %></h4>
        <%= concert.city %> - <%= concert.country %>
        <hr>
      <% end %>
    <% else %>
      <i>No concert yet</i>
    <% end %>
  </div>
</div>

<%= paginate @concerts, :theme => 'twitter-bootstrap-3' %>

app/views/concerts/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Concerts", concerts_path %></li>
  <li class="active"><%= @concert.name.capitalize %></li>
</ol>

<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @concert.name.capitalize %></h3>
      </div>
      <div class="panel-body">
        <p class="text-justify"><%= @concert.description.html_safe %></p>
      </div> 
    </div>
  </div>
  <div class="col-md-3">
      <%= render "concerts/location" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render "concerts/concerts" %>
    <%= render "medias/medias" %>
  </div>
  <div class="col-md-5">
    <%= render "posts/posts" %>
  </div>
  <div class="col-md-3">
    <%= render "utils/soundcloud" %>
    <%= render "albums/featured" %>
    <%= render "utils/like" %>
    <%= render "sponsors/sponsors" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paranoid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Paranoid Sky</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= render "utils/nav" %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <div class="footer">
    <div class="container">
      <span class="brand" href="#">Paranoid Sky</span><span class="pull-right">Crafted by @gmourier</span>
    </div>
  </div>
</body>
</html>

app/views/medias/_medias.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Gallery</h3>
  </div>
  <div class="panel-body">
    <% if !@medias.empty? %>
    <% @medias.each do |media| %>
      <%= link_to image_tag(media.file.url(:thumb), size: "50", alt: media.title.capitalize), media.file.url(:original), class: "fancybox" %>
    <% end %>
    <% else %>
      <i>No media yet</i>
    <% end %>
  </div>
  <div class="panel-footer">
    <%= link_to "All medias", medias_path %>
  </div>
</div>

app/views/medias/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Gallery</li>
</ol>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Gallery</h3>
  </div>
  <div class="panel-body">
    <% @medias.each do |media| %>
      <%= link_to image_tag(media.file.url(:thumb), size: "50", alt: media.title.capitalize), 
          media.file.url(:original), {
            :rel => "gallery", 
            :class => "fancybox"
          }
      %>
    <% end %>
  </div>
</div>

app/views/pages/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active"><%= @page.title.capitalize %></li>
</ol>

<div class="panel panel-default">
  <div class="panel-body">
    <h1><%= @page.title.capitalize %></h1>
    <p class="text-justify">
      <%= @page.content.html_safe %>
    </p>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Lasts Posts</h3>
  </div>
  <div class="panel-body">
    <% if !@posts.empty? %>
      <% @posts.each do |post| %>
        <div class="row">
          <div class="col-xs-12">
            <h4 class="media-heading"><%= link_to post.title, post %></h4>
            <p class="text-justify"><%= truncate(strip_tags(post.content), length: 200) %></p>
            <p class="pull-right">
              <% post.tags.each do |t| %>
              <span class="label label-default"><%= t.label %></span> 
              <% end %>
            </p>
            <ul class="list-inline">
              <li><a href="#"><%= distance_of_time_in_words_to_now(post.created_at).capitalize %> ago</a></li>
            </ul>
          </div>
        </div>
        <hr>
      <% end %>
    <% else %>
      <i>No post yet</i>
    <% end %>
  </div>
  <div class="panel-footer">
    <%= link_to "All posts", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Posts</li>
</ol>



<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Posts</h3>
  </div>
  <div class="panel-body">
    <% if !@posts.empty? %>
      <% @posts.each do |post| %>
        <h4><%= link_to post.title.capitalize, post %></h4>
        <%= post.created_at.strftime("%D") %>
        <hr>
      <% end %>
    <% else %>
      <i>No post yet</i>
    <% end %>
  </div>
</div>

<%= paginate @posts, :theme => 'twitter-bootstrap-3' %>

app/views/posts/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Posts", posts_path %></li>
  <li class="active"><%= @post.title %></li>
</ol>

<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <h1><%= @post.title.capitalize %></h1>
        <p class="text-justify"><%= @post.content.html_safe %></p>
        </br>
        <a href="#"><%= distance_of_time_in_words_to_now(@post.created_at) %> ago</a>
      </div>
      <div class="panel-footer">
        <p>
          <span class="label label-default">keyword</span> 
          <span class="label label-default">tag</span> 
          <span class="label label-default">post</span>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <%= render "utils/soundcloud" %>
  </div>
</div>

app/views/sponsors/_sponsors.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Endorsed by</h3>
  </div>
  <div class="panel-body">
    <% if !@sponsors.empty? %>
      <% @sponsors.each do |sponsor| %>
        <%= image_tag sponsor.logo.url(:thumb) %>
      <% end %>
    <% else %>
      <i>No sponsors yet</i>
    <% end %>
  </div>
  <div class="panel-footer">
    <%= link_to "All sponsors", sponsors_path %>
  </div>
</div>

app/views/sponsors/show.html.erb
<%= link_to 'Back', sponsors_path %>

app/views/utils/_like.html.erb
<div class="fb-like-box" 
    data-href="https://www.facebook.com/Paranoidsky" 
    data-colorscheme="light" data-show-faces="true" 
    data-header="false" data-stream="false" 
    data-show-border="false">
</div>

app/views/utils/_nav.html.erb
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Albums", albums_path %></li>
<li><%= link_to "Posts", posts_path %></li>
<li><%= link_to "Concerts", concerts_path %></li>
<li><%= link_to "Gallery", medias_path %></li>
<!-- Render Pages navigation -->
<% generate_nav.each do |page| %>
    <li><%= link_to page.title.capitalize, page %></li>
<% end %>

app/views/utils/_soundcloud.html.erb
<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/170022125&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>